// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heroball.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	Position             string   `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type Competition struct {
	CompetitionId        int32    `protobuf:"varint,1,opt,name=CompetitionId,proto3" json:"CompetitionId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	Division             string   `protobuf:"bytes,3,opt,name=Division,proto3" json:"Division"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Competition) Reset()         { *m = Competition{} }
func (m *Competition) String() string { return proto.CompactTextString(m) }
func (*Competition) ProtoMessage()    {}
func (*Competition) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{1}
}
func (m *Competition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Competition.Unmarshal(m, b)
}
func (m *Competition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Competition.Marshal(b, m, deterministic)
}
func (dst *Competition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Competition.Merge(dst, src)
}
func (m *Competition) XXX_Size() int {
	return xxx_messageInfo_Competition.Size(m)
}
func (m *Competition) XXX_DiscardUnknown() {
	xxx_messageInfo_Competition.DiscardUnknown(m)
}

var xxx_messageInfo_Competition proto.InternalMessageInfo

func (m *Competition) GetCompetitionId() int32 {
	if m != nil {
		return m.CompetitionId
	}
	return 0
}

func (m *Competition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Competition) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

type Team struct {
	TeamId               int32    `protobuf:"varint,1,opt,name=TeamId,proto3" json:"TeamId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{2}
}
func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (dst *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(dst, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Location struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=LocationId,proto3" json:"LocationId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{3}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PlayerStats struct {
	StatsId                 int32    `protobuf:"varint,1,opt,name=StatsId,proto3" json:"StatsId"`
	TwoPointFGA             int32    `protobuf:"varint,2,opt,name=TwoPointFGA,proto3" json:"TwoPointFGA"`
	TwoPointFGM             int32    `protobuf:"varint,3,opt,name=TwoPointFGM,proto3" json:"TwoPointFGM"`
	ThreePointFGA           int32    `protobuf:"varint,4,opt,name=ThreePointFGA,proto3" json:"ThreePointFGA"`
	ThreePointFGM           int32    `protobuf:"varint,5,opt,name=ThreePointFGM,proto3" json:"ThreePointFGM"`
	FreeThrowsAttempted     int32    `protobuf:"varint,6,opt,name=FreeThrowsAttempted,proto3" json:"FreeThrowsAttempted"`
	FreeThrowsMade          int32    `protobuf:"varint,7,opt,name=FreeThrowsMade,proto3" json:"FreeThrowsMade"`
	OffensiveRebounds       int32    `protobuf:"varint,8,opt,name=OffensiveRebounds,proto3" json:"OffensiveRebounds"`
	DefensiveRebounds       int32    `protobuf:"varint,9,opt,name=DefensiveRebounds,proto3" json:"DefensiveRebounds"`
	Assists                 int32    `protobuf:"varint,10,opt,name=Assists,proto3" json:"Assists"`
	Blocks                  int32    `protobuf:"varint,11,opt,name=Blocks,proto3" json:"Blocks"`
	Steals                  int32    `protobuf:"varint,12,opt,name=Steals,proto3" json:"Steals"`
	Turnovers               int32    `protobuf:"varint,13,opt,name=Turnovers,proto3" json:"Turnovers"`
	RegularFoulsForced      int32    `protobuf:"varint,14,opt,name=RegularFoulsForced,proto3" json:"RegularFoulsForced"`
	RegularFoulsCommitted   int32    `protobuf:"varint,15,opt,name=RegularFoulsCommitted,proto3" json:"RegularFoulsCommitted"`
	TechnicalFoulsCommitted int32    `protobuf:"varint,16,opt,name=TechnicalFoulsCommitted,proto3" json:"TechnicalFoulsCommitted"`
	MinutesPlayed           int32    `protobuf:"varint,17,opt,name=MinutesPlayed,proto3" json:"MinutesPlayed"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *PlayerStats) Reset()         { *m = PlayerStats{} }
func (m *PlayerStats) String() string { return proto.CompactTextString(m) }
func (*PlayerStats) ProtoMessage()    {}
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{4}
}
func (m *PlayerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStats.Unmarshal(m, b)
}
func (m *PlayerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStats.Marshal(b, m, deterministic)
}
func (dst *PlayerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStats.Merge(dst, src)
}
func (m *PlayerStats) XXX_Size() int {
	return xxx_messageInfo_PlayerStats.Size(m)
}
func (m *PlayerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStats proto.InternalMessageInfo

func (m *PlayerStats) GetStatsId() int32 {
	if m != nil {
		return m.StatsId
	}
	return 0
}

func (m *PlayerStats) GetTwoPointFGA() int32 {
	if m != nil {
		return m.TwoPointFGA
	}
	return 0
}

func (m *PlayerStats) GetTwoPointFGM() int32 {
	if m != nil {
		return m.TwoPointFGM
	}
	return 0
}

func (m *PlayerStats) GetThreePointFGA() int32 {
	if m != nil {
		return m.ThreePointFGA
	}
	return 0
}

func (m *PlayerStats) GetThreePointFGM() int32 {
	if m != nil {
		return m.ThreePointFGM
	}
	return 0
}

func (m *PlayerStats) GetFreeThrowsAttempted() int32 {
	if m != nil {
		return m.FreeThrowsAttempted
	}
	return 0
}

func (m *PlayerStats) GetFreeThrowsMade() int32 {
	if m != nil {
		return m.FreeThrowsMade
	}
	return 0
}

func (m *PlayerStats) GetOffensiveRebounds() int32 {
	if m != nil {
		return m.OffensiveRebounds
	}
	return 0
}

func (m *PlayerStats) GetDefensiveRebounds() int32 {
	if m != nil {
		return m.DefensiveRebounds
	}
	return 0
}

func (m *PlayerStats) GetAssists() int32 {
	if m != nil {
		return m.Assists
	}
	return 0
}

func (m *PlayerStats) GetBlocks() int32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *PlayerStats) GetSteals() int32 {
	if m != nil {
		return m.Steals
	}
	return 0
}

func (m *PlayerStats) GetTurnovers() int32 {
	if m != nil {
		return m.Turnovers
	}
	return 0
}

func (m *PlayerStats) GetRegularFoulsForced() int32 {
	if m != nil {
		return m.RegularFoulsForced
	}
	return 0
}

func (m *PlayerStats) GetRegularFoulsCommitted() int32 {
	if m != nil {
		return m.RegularFoulsCommitted
	}
	return 0
}

func (m *PlayerStats) GetTechnicalFoulsCommitted() int32 {
	if m != nil {
		return m.TechnicalFoulsCommitted
	}
	return 0
}

func (m *PlayerStats) GetMinutesPlayed() int32 {
	if m != nil {
		return m.MinutesPlayed
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{5}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PlayerProfile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"`
	YearStarted          int32    `protobuf:"varint,2,opt,name=YearStarted,proto3" json:"YearStarted"`
	Position             string   `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerProfile) Reset()         { *m = PlayerProfile{} }
func (m *PlayerProfile) String() string { return proto.CompactTextString(m) }
func (*PlayerProfile) ProtoMessage()    {}
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{6}
}
func (m *PlayerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerProfile.Unmarshal(m, b)
}
func (m *PlayerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerProfile.Marshal(b, m, deterministic)
}
func (dst *PlayerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerProfile.Merge(dst, src)
}
func (m *PlayerProfile) XXX_Size() int {
	return xxx_messageInfo_PlayerProfile.Size(m)
}
func (m *PlayerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerProfile proto.InternalMessageInfo

func (m *PlayerProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerProfile) GetYearStarted() int32 {
	if m != nil {
		return m.YearStarted
	}
	return 0
}

func (m *PlayerProfile) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *PlayerProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PlayerGameStats struct {
	PlayerId             int32        `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	TeamId               int32        `protobuf:"varint,2,opt,name=TeamId,proto3" json:"TeamId"`
	Stats                *PlayerStats `protobuf:"bytes,3,opt,name=Stats,proto3" json:"Stats"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlayerGameStats) Reset()         { *m = PlayerGameStats{} }
func (m *PlayerGameStats) String() string { return proto.CompactTextString(m) }
func (*PlayerGameStats) ProtoMessage()    {}
func (*PlayerGameStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{7}
}
func (m *PlayerGameStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerGameStats.Unmarshal(m, b)
}
func (m *PlayerGameStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerGameStats.Marshal(b, m, deterministic)
}
func (dst *PlayerGameStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerGameStats.Merge(dst, src)
}
func (m *PlayerGameStats) XXX_Size() int {
	return xxx_messageInfo_PlayerGameStats.Size(m)
}
func (m *PlayerGameStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerGameStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerGameStats proto.InternalMessageInfo

func (m *PlayerGameStats) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerGameStats) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *PlayerGameStats) GetStats() *PlayerStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type PlayerGame struct {
	Game                 *Game            `protobuf:"bytes,1,opt,name=Game,proto3" json:"Game"`
	Stats                *PlayerGameStats `protobuf:"bytes,2,opt,name=Stats,proto3" json:"Stats"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlayerGame) Reset()         { *m = PlayerGame{} }
func (m *PlayerGame) String() string { return proto.CompactTextString(m) }
func (*PlayerGame) ProtoMessage()    {}
func (*PlayerGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{8}
}
func (m *PlayerGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerGame.Unmarshal(m, b)
}
func (m *PlayerGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerGame.Marshal(b, m, deterministic)
}
func (dst *PlayerGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerGame.Merge(dst, src)
}
func (m *PlayerGame) XXX_Size() int {
	return xxx_messageInfo_PlayerGame.Size(m)
}
func (m *PlayerGame) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerGame.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerGame proto.InternalMessageInfo

func (m *PlayerGame) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func (m *PlayerGame) GetStats() *PlayerGameStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Game struct {
	GameId               int32        `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId"`
	HomeTeam             *Team        `protobuf:"bytes,2,opt,name=HomeTeam,proto3" json:"HomeTeam"`
	AwayTeam             *Team        `protobuf:"bytes,3,opt,name=AwayTeam,proto3" json:"AwayTeam"`
	Location             *Location    `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location"`
	Competition          *Competition `protobuf:"bytes,5,opt,name=Competition,proto3" json:"Competition"`
	GameTime             string       `protobuf:"bytes,7,opt,name=GameTime,proto3" json:"GameTime"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{9}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (dst *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(dst, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *Game) GetHomeTeam() *Team {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *Game) GetAwayTeam() *Team {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

func (m *Game) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Game) GetCompetition() *Competition {
	if m != nil {
		return m.Competition
	}
	return nil
}

func (m *Game) GetGameTime() string {
	if m != nil {
		return m.GameTime
	}
	return ""
}

type PlayerInfo struct {
	PlayerId             int32          `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	Profile              *PlayerProfile `protobuf:"bytes,2,opt,name=Profile,proto3" json:"Profile"`
	RecentGames          []*PlayerGame  `protobuf:"bytes,3,rep,name=RecentGames,proto3" json:"RecentGames"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{10}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerInfo) GetProfile() *PlayerProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *PlayerInfo) GetRecentGames() []*PlayerGame {
	if m != nil {
		return m.RecentGames
	}
	return nil
}

type GameInfo struct {
	Game                 *Game              `protobuf:"bytes,1,opt,name=Game,proto3" json:"Game"`
	PlayerStats          []*PlayerGameStats `protobuf:"bytes,2,rep,name=PlayerStats,proto3" json:"PlayerStats"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GameInfo) Reset()         { *m = GameInfo{} }
func (m *GameInfo) String() string { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()    {}
func (*GameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{11}
}
func (m *GameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfo.Unmarshal(m, b)
}
func (m *GameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfo.Marshal(b, m, deterministic)
}
func (dst *GameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfo.Merge(dst, src)
}
func (m *GameInfo) XXX_Size() int {
	return xxx_messageInfo_GameInfo.Size(m)
}
func (m *GameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfo proto.InternalMessageInfo

func (m *GameInfo) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func (m *GameInfo) GetPlayerStats() []*PlayerGameStats {
	if m != nil {
		return m.PlayerStats
	}
	return nil
}

type GetPlayerInfoRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerInfoRequest) Reset()         { *m = GetPlayerInfoRequest{} }
func (m *GetPlayerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerInfoRequest) ProtoMessage()    {}
func (*GetPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{12}
}
func (m *GetPlayerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerInfoRequest.Unmarshal(m, b)
}
func (m *GetPlayerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetPlayerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerInfoRequest.Merge(dst, src)
}
func (m *GetPlayerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerInfoRequest.Size(m)
}
func (m *GetPlayerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerInfoRequest proto.InternalMessageInfo

func (m *GetPlayerInfoRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type GetGameInfoRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameInfoRequest) Reset()         { *m = GetGameInfoRequest{} }
func (m *GetGameInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetGameInfoRequest) ProtoMessage()    {}
func (*GetGameInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_0dc862c8bef646a3, []int{13}
}
func (m *GetGameInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameInfoRequest.Unmarshal(m, b)
}
func (m *GetGameInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetGameInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameInfoRequest.Merge(dst, src)
}
func (m *GetGameInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetGameInfoRequest.Size(m)
}
func (m *GetGameInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameInfoRequest proto.InternalMessageInfo

func (m *GetGameInfoRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func init() {
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*Competition)(nil), "pb.Competition")
	proto.RegisterType((*Team)(nil), "pb.Team")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*PlayerStats)(nil), "pb.PlayerStats")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*PlayerProfile)(nil), "pb.PlayerProfile")
	proto.RegisterType((*PlayerGameStats)(nil), "pb.PlayerGameStats")
	proto.RegisterType((*PlayerGame)(nil), "pb.PlayerGame")
	proto.RegisterType((*Game)(nil), "pb.Game")
	proto.RegisterType((*PlayerInfo)(nil), "pb.PlayerInfo")
	proto.RegisterType((*GameInfo)(nil), "pb.GameInfo")
	proto.RegisterType((*GetPlayerInfoRequest)(nil), "pb.GetPlayerInfoRequest")
	proto.RegisterType((*GetGameInfoRequest)(nil), "pb.GetGameInfoRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HeroBallServiceClient is the client API for HeroBallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeroBallServiceClient interface {
	GetPlayerInfo(ctx context.Context, in *GetPlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfo, error)
	GetGameInfo(ctx context.Context, in *GetGameInfoRequest, opts ...grpc.CallOption) (*GameInfo, error)
}

type heroBallServiceClient struct {
	cc *grpc.ClientConn
}

func NewHeroBallServiceClient(cc *grpc.ClientConn) HeroBallServiceClient {
	return &heroBallServiceClient{cc}
}

func (c *heroBallServiceClient) GetPlayerInfo(ctx context.Context, in *GetPlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfo, error) {
	out := new(PlayerInfo)
	err := c.cc.Invoke(ctx, "/pb.HeroBallService/GetPlayerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heroBallServiceClient) GetGameInfo(ctx context.Context, in *GetGameInfoRequest, opts ...grpc.CallOption) (*GameInfo, error) {
	out := new(GameInfo)
	err := c.cc.Invoke(ctx, "/pb.HeroBallService/GetGameInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeroBallServiceServer is the server API for HeroBallService service.
type HeroBallServiceServer interface {
	GetPlayerInfo(context.Context, *GetPlayerInfoRequest) (*PlayerInfo, error)
	GetGameInfo(context.Context, *GetGameInfoRequest) (*GameInfo, error)
}

func RegisterHeroBallServiceServer(s *grpc.Server, srv HeroBallServiceServer) {
	s.RegisterService(&_HeroBallService_serviceDesc, srv)
}

func _HeroBallService_GetPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeroBallServiceServer).GetPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HeroBallService/GetPlayerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeroBallServiceServer).GetPlayerInfo(ctx, req.(*GetPlayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeroBallService_GetGameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeroBallServiceServer).GetGameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HeroBallService/GetGameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeroBallServiceServer).GetGameInfo(ctx, req.(*GetGameInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeroBallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HeroBallService",
	HandlerType: (*HeroBallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerInfo",
			Handler:    _HeroBallService_GetPlayerInfo_Handler,
		},
		{
			MethodName: "GetGameInfo",
			Handler:    _HeroBallService_GetGameInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heroball.proto",
}

func init() { proto.RegisterFile("heroball.proto", fileDescriptor_heroball_0dc862c8bef646a3) }

var fileDescriptor_heroball_0dc862c8bef646a3 = []byte{
	// 862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xd6, 0x78, 0xed, 0xc4, 0xa9, 0xc9, 0x0f, 0xe9, 0x40, 0x68, 0x59, 0xd1, 0x2a, 0x1a, 0x2d,
	0x28, 0xc0, 0x2a, 0xde, 0x35, 0x20, 0x21, 0x0e, 0x48, 0xd9, 0x0d, 0xf1, 0xae, 0x84, 0x21, 0x4c,
	0xcc, 0x61, 0x4f, 0xa8, 0x3d, 0x2e, 0x3b, 0x23, 0x66, 0xa6, 0x87, 0xe9, 0xb6, 0xa3, 0x5c, 0xe1,
	0xc0, 0x03, 0x70, 0xe4, 0x61, 0x78, 0x08, 0x1e, 0x01, 0x1e, 0x04, 0x75, 0xf5, 0xfc, 0x3a, 0x8e,
	0x4f, 0x9e, 0xfa, 0xbe, 0xaf, 0xbe, 0xae, 0xae, 0xee, 0x6a, 0x19, 0xf6, 0x6f, 0x31, 0x93, 0x13,
	0x11, 0x45, 0xe7, 0x69, 0x26, 0xb5, 0x64, 0xad, 0x74, 0xd2, 0x3b, 0x99, 0x4b, 0x39, 0x8f, 0xb0,
	0x2f, 0xd2, 0xb0, 0x2f, 0x92, 0x44, 0x6a, 0xa1, 0x43, 0x99, 0x28, 0xab, 0xf0, 0xc6, 0xb0, 0x75,
	0x1d, 0x89, 0x7b, 0xcc, 0x58, 0x0f, 0xba, 0xf6, 0xeb, 0xed, 0x94, 0x3b, 0xa7, 0xce, 0x59, 0xc7,
	0x2f, 0x63, 0xc6, 0xa0, 0xfd, 0xbd, 0x88, 0x91, 0xb7, 0x4e, 0x9d, 0xb3, 0x1d, 0x9f, 0xbe, 0x49,
	0x2f, 0x55, 0x68, 0xcc, 0xf8, 0x13, 0xc2, 0xcb, 0xd8, 0x0b, 0xc0, 0x7d, 0x2d, 0xe3, 0x14, 0x35,
	0x85, 0xec, 0x19, 0xec, 0xd5, 0xc2, 0xd2, 0xbf, 0x09, 0x3e, 0xb6, 0xc8, 0x65, 0xb8, 0x0c, 0x55,
	0x6d, 0x91, 0x22, 0xf6, 0x06, 0xd0, 0x1e, 0xa3, 0x88, 0xd9, 0x31, 0x6c, 0x99, 0xdf, 0xd2, 0x36,
	0x8f, 0xd6, 0xf9, 0x79, 0xdf, 0x40, 0xf7, 0x3b, 0x19, 0x50, 0x07, 0xd8, 0x53, 0x80, 0xe2, 0xbb,
	0xcc, 0xad, 0x21, 0x6b, 0xf3, 0xff, 0xea, 0x80, 0x6b, 0xbb, 0x72, 0xa3, 0x85, 0x56, 0x8c, 0xc3,
	0x36, 0x7d, 0x94, 0x06, 0x45, 0xc8, 0x4e, 0xc1, 0x1d, 0xdf, 0xc9, 0x6b, 0x19, 0x26, 0xfa, 0x6a,
	0x78, 0x41, 0x26, 0x1d, 0xbf, 0x0e, 0x35, 0x15, 0x23, 0xda, 0x5e, 0x43, 0x31, 0x32, 0x7d, 0x1b,
	0xdf, 0x66, 0x88, 0xa5, 0x4b, 0xdb, 0xf6, 0xad, 0x01, 0xae, 0xaa, 0x46, 0xbc, 0xf3, 0x50, 0x35,
	0x62, 0x2f, 0xe0, 0xe8, 0x2a, 0x43, 0x1c, 0xdf, 0x66, 0xf2, 0x4e, 0x5d, 0x68, 0x8d, 0x71, 0xaa,
	0x71, 0xca, 0xb7, 0x48, 0xbb, 0x8e, 0x62, 0x1f, 0xc3, 0x7e, 0x05, 0x8f, 0xc4, 0x14, 0xf9, 0x36,
	0x89, 0x57, 0x50, 0xf6, 0x1c, 0x0e, 0x7f, 0x98, 0xcd, 0x30, 0x51, 0xe1, 0x12, 0x7d, 0x9c, 0xc8,
	0x45, 0x32, 0x55, 0xbc, 0x4b, 0xd2, 0x87, 0x84, 0x51, 0x5f, 0xe2, 0xaa, 0x7a, 0xc7, 0xaa, 0x1f,
	0x10, 0xa6, 0xbf, 0x17, 0x4a, 0x85, 0x4a, 0x2b, 0x0e, 0xb6, 0xbf, 0x79, 0x68, 0x4e, 0xfd, 0x55,
	0x24, 0x83, 0x5f, 0x14, 0x77, 0xed, 0xa9, 0xdb, 0xc8, 0xe0, 0x37, 0x1a, 0x45, 0xa4, 0xf8, 0xae,
	0xc5, 0x6d, 0xc4, 0x4e, 0x60, 0x67, 0xbc, 0xc8, 0x12, 0xb9, 0xc4, 0x4c, 0xf1, 0x3d, 0xa2, 0x2a,
	0x80, 0x9d, 0x03, 0xf3, 0x71, 0xbe, 0x88, 0x44, 0x76, 0x25, 0x17, 0x91, 0xba, 0x92, 0x59, 0x80,
	0x53, 0xbe, 0x4f, 0xb2, 0x35, 0x0c, 0xfb, 0x02, 0x3e, 0xa8, 0xa3, 0xaf, 0x65, 0x1c, 0x87, 0xda,
	0xf4, 0xf3, 0x80, 0x52, 0xd6, 0x93, 0xec, 0x2b, 0xf8, 0x70, 0x8c, 0xc1, 0x6d, 0x12, 0x06, 0x22,
	0x5a, 0xc9, 0x7b, 0x8f, 0xf2, 0x1e, 0xa3, 0xcd, 0x19, 0x8f, 0xc2, 0x64, 0xa1, 0x51, 0xd1, 0xed,
	0x9b, 0xf2, 0x43, 0x7b, 0xc6, 0x0d, 0xd0, 0xdb, 0x86, 0xce, 0xb7, 0x71, 0xaa, 0xef, 0xbd, 0xdf,
	0x1d, 0xd8, 0xb3, 0xd7, 0xf4, 0x3a, 0x93, 0xb3, 0x30, 0xc2, 0xf2, 0x32, 0x3b, 0xb5, 0xe1, 0x3a,
	0x05, 0xf7, 0x1d, 0x0a, 0x73, 0x93, 0x33, 0x53, 0x42, 0x7e, 0x45, 0x6b, 0xd0, 0xa6, 0x19, 0x37,
	0xd9, 0x97, 0xa8, 0x82, 0x2c, 0x4c, 0x89, 0x6e, 0x13, 0x5d, 0x87, 0xbc, 0x08, 0x0e, 0x6c, 0x11,
	0x43, 0x11, 0xa3, 0x9d, 0x97, 0x4d, 0x8f, 0x4c, 0x35, 0xc7, 0xad, 0xc6, 0x1c, 0x7f, 0x04, 0x1d,
	0x4a, 0xa6, 0x0a, 0xdc, 0xc1, 0xc1, 0x79, 0x3a, 0x39, 0xaf, 0xcd, 0xa0, 0x6f, 0x59, 0xef, 0x27,
	0x80, 0x6a, 0x35, 0x76, 0x02, 0xed, 0x61, 0xb1, 0x5f, 0x77, 0xd0, 0x35, 0x39, 0x26, 0xf6, 0x09,
	0x65, 0x9f, 0x14, 0x96, 0x2d, 0xa2, 0x8f, 0x2a, 0xcb, 0xb2, 0xd4, 0xc2, 0xf6, 0x5f, 0xc7, 0x3a,
	0x99, 0xf2, 0xcc, 0x6f, 0xf5, 0xcc, 0xd8, 0x88, 0x3d, 0x83, 0xee, 0x1b, 0x19, 0xa3, 0x29, 0x36,
	0xb7, 0xa3, 0xd5, 0x4c, 0xec, 0x97, 0x8c, 0x51, 0x5d, 0xdc, 0x89, 0x7b, 0x52, 0x3d, 0x59, 0x55,
	0x15, 0x0c, 0x3b, 0xab, 0x9e, 0x27, 0x6a, 0xa8, 0x3b, 0xd8, 0x35, 0xaa, 0x02, 0xf3, 0xab, 0xc7,
	0xeb, 0x65, 0xe3, 0x85, 0xa5, 0x91, 0xcf, 0x5b, 0x53, 0x83, 0xfd, 0xc6, 0x2b, 0xdc, 0x83, 0xae,
	0x29, 0x79, 0x1c, 0xc6, 0x76, 0x92, 0x77, 0xfc, 0x32, 0xf6, 0xfe, 0x70, 0x8a, 0xee, 0xbd, 0x4d,
	0x66, 0x72, 0xe3, 0x31, 0x7d, 0x06, 0xdb, 0xf9, 0xa5, 0xca, 0xb7, 0x7b, 0x58, 0x75, 0x2f, 0x27,
	0xfc, 0x42, 0xc1, 0x5e, 0x80, 0xeb, 0x63, 0x80, 0x89, 0x36, 0x2b, 0x99, 0x13, 0x7c, 0x72, 0xe6,
	0x0e, 0xf6, 0x9b, 0xed, 0xf6, 0xeb, 0x12, 0xef, 0x67, 0x5b, 0x25, 0x95, 0xb1, 0xf9, 0x10, 0xbf,
	0x6c, 0x3c, 0xc5, 0xbc, 0x45, 0xde, 0x6b, 0x8f, 0xb2, 0xae, 0xf3, 0x06, 0xf0, 0xfe, 0x10, 0x75,
	0xb5, 0x59, 0x1f, 0x7f, 0x5d, 0xa0, 0xd2, 0x9b, 0xf6, 0xec, 0x3d, 0x07, 0x36, 0x44, 0x5d, 0xd4,
	0x55, 0x64, 0x3c, 0x72, 0x23, 0x06, 0x7f, 0x3b, 0x70, 0xf0, 0x06, 0x33, 0xf9, 0x4a, 0x44, 0xd1,
	0x0d, 0x66, 0xcb, 0x30, 0x40, 0xf6, 0x0e, 0xf6, 0x1a, 0xab, 0x32, 0x4e, 0xbb, 0x59, 0x53, 0x48,
	0xaf, 0xd6, 0x1e, 0x03, 0x7b, 0x4f, 0x7f, 0xfb, 0xe7, 0xbf, 0x3f, 0x5b, 0xdc, 0x3b, 0xea, 0x2f,
	0x5f, 0xf6, 0xe7, 0xa8, 0xfb, 0x29, 0x71, 0xfd, 0x30, 0x99, 0xc9, 0xaf, 0x9d, 0x4f, 0xd9, 0x8f,
	0xe0, 0xd6, 0x8a, 0x63, 0xc7, 0xb9, 0xf1, 0x4a, 0xb5, 0xbd, 0xdd, 0xa2, 0x7d, 0x64, 0x7a, 0x42,
	0xa6, 0xc7, 0xde, 0x61, 0x61, 0x3a, 0x17, 0x31, 0x16, 0x96, 0x93, 0x2d, 0xfa, 0x73, 0xf0, 0xf9,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x38, 0xe1, 0xc2, 0x50, 0x08, 0x00, 0x00,
}
