// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heroball.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	Position             string   `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type League struct {
	LeagueId             int32    `protobuf:"varint,1,opt,name=LeagueId,proto3" json:"LeagueId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	Division             string   `protobuf:"bytes,3,opt,name=Division,proto3" json:"Division"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *League) Reset()         { *m = League{} }
func (m *League) String() string { return proto.CompactTextString(m) }
func (*League) ProtoMessage()    {}
func (*League) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{1}
}
func (m *League) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_League.Unmarshal(m, b)
}
func (m *League) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_League.Marshal(b, m, deterministic)
}
func (dst *League) XXX_Merge(src proto.Message) {
	xxx_messageInfo_League.Merge(dst, src)
}
func (m *League) XXX_Size() int {
	return xxx_messageInfo_League.Size(m)
}
func (m *League) XXX_DiscardUnknown() {
	xxx_messageInfo_League.DiscardUnknown(m)
}

var xxx_messageInfo_League proto.InternalMessageInfo

func (m *League) GetLeagueId() int32 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

func (m *League) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *League) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

type Competition struct {
	League               *League  `protobuf:"bytes,1,opt,name=League,proto3" json:"League"`
	CompetitionId        int32    `protobuf:"varint,2,opt,name=CompetitionId,proto3" json:"CompetitionId"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Competition) Reset()         { *m = Competition{} }
func (m *Competition) String() string { return proto.CompactTextString(m) }
func (*Competition) ProtoMessage()    {}
func (*Competition) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{2}
}
func (m *Competition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Competition.Unmarshal(m, b)
}
func (m *Competition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Competition.Marshal(b, m, deterministic)
}
func (dst *Competition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Competition.Merge(dst, src)
}
func (m *Competition) XXX_Size() int {
	return xxx_messageInfo_Competition.Size(m)
}
func (m *Competition) XXX_DiscardUnknown() {
	xxx_messageInfo_Competition.DiscardUnknown(m)
}

var xxx_messageInfo_Competition proto.InternalMessageInfo

func (m *Competition) GetLeague() *League {
	if m != nil {
		return m.League
	}
	return nil
}

func (m *Competition) GetCompetitionId() int32 {
	if m != nil {
		return m.CompetitionId
	}
	return 0
}

func (m *Competition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Team struct {
	TeamId               int32    `protobuf:"varint,1,opt,name=TeamId,proto3" json:"TeamId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{3}
}
func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (dst *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(dst, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CompetitionTeam struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=Team,proto3" json:"Team"`
	Won                  int32    `protobuf:"varint,2,opt,name=Won,proto3" json:"Won"`
	Drawn                int32    `protobuf:"varint,3,opt,name=Drawn,proto3" json:"Drawn"`
	Lost                 int32    `protobuf:"varint,4,opt,name=Lost,proto3" json:"Lost"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompetitionTeam) Reset()         { *m = CompetitionTeam{} }
func (m *CompetitionTeam) String() string { return proto.CompactTextString(m) }
func (*CompetitionTeam) ProtoMessage()    {}
func (*CompetitionTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{4}
}
func (m *CompetitionTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompetitionTeam.Unmarshal(m, b)
}
func (m *CompetitionTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompetitionTeam.Marshal(b, m, deterministic)
}
func (dst *CompetitionTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompetitionTeam.Merge(dst, src)
}
func (m *CompetitionTeam) XXX_Size() int {
	return xxx_messageInfo_CompetitionTeam.Size(m)
}
func (m *CompetitionTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_CompetitionTeam.DiscardUnknown(m)
}

var xxx_messageInfo_CompetitionTeam proto.InternalMessageInfo

func (m *CompetitionTeam) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *CompetitionTeam) GetWon() int32 {
	if m != nil {
		return m.Won
	}
	return 0
}

func (m *CompetitionTeam) GetDrawn() int32 {
	if m != nil {
		return m.Drawn
	}
	return 0
}

func (m *CompetitionTeam) GetLost() int32 {
	if m != nil {
		return m.Lost
	}
	return 0
}

type Location struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=LocationId,proto3" json:"LocationId"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{5}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Stats struct {
	StatsId                 int32    `protobuf:"varint,1,opt,name=StatsId,proto3" json:"StatsId"`
	TwoPointFGA             int32    `protobuf:"varint,2,opt,name=TwoPointFGA,proto3" json:"TwoPointFGA"`
	TwoPointFGM             int32    `protobuf:"varint,3,opt,name=TwoPointFGM,proto3" json:"TwoPointFGM"`
	ThreePointFGA           int32    `protobuf:"varint,4,opt,name=ThreePointFGA,proto3" json:"ThreePointFGA"`
	ThreePointFGM           int32    `protobuf:"varint,5,opt,name=ThreePointFGM,proto3" json:"ThreePointFGM"`
	FreeThrowsAttempted     int32    `protobuf:"varint,6,opt,name=FreeThrowsAttempted,proto3" json:"FreeThrowsAttempted"`
	FreeThrowsMade          int32    `protobuf:"varint,7,opt,name=FreeThrowsMade,proto3" json:"FreeThrowsMade"`
	OffensiveRebounds       int32    `protobuf:"varint,8,opt,name=OffensiveRebounds,proto3" json:"OffensiveRebounds"`
	DefensiveRebounds       int32    `protobuf:"varint,9,opt,name=DefensiveRebounds,proto3" json:"DefensiveRebounds"`
	Assists                 int32    `protobuf:"varint,10,opt,name=Assists,proto3" json:"Assists"`
	Blocks                  int32    `protobuf:"varint,11,opt,name=Blocks,proto3" json:"Blocks"`
	Steals                  int32    `protobuf:"varint,12,opt,name=Steals,proto3" json:"Steals"`
	Turnovers               int32    `protobuf:"varint,13,opt,name=Turnovers,proto3" json:"Turnovers"`
	RegularFoulsForced      int32    `protobuf:"varint,14,opt,name=RegularFoulsForced,proto3" json:"RegularFoulsForced"`
	RegularFoulsCommitted   int32    `protobuf:"varint,15,opt,name=RegularFoulsCommitted,proto3" json:"RegularFoulsCommitted"`
	TechnicalFoulsCommitted int32    `protobuf:"varint,16,opt,name=TechnicalFoulsCommitted,proto3" json:"TechnicalFoulsCommitted"`
	MinutesPlayed           int32    `protobuf:"varint,17,opt,name=MinutesPlayed,proto3" json:"MinutesPlayed"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{6}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (dst *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(dst, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetStatsId() int32 {
	if m != nil {
		return m.StatsId
	}
	return 0
}

func (m *Stats) GetTwoPointFGA() int32 {
	if m != nil {
		return m.TwoPointFGA
	}
	return 0
}

func (m *Stats) GetTwoPointFGM() int32 {
	if m != nil {
		return m.TwoPointFGM
	}
	return 0
}

func (m *Stats) GetThreePointFGA() int32 {
	if m != nil {
		return m.ThreePointFGA
	}
	return 0
}

func (m *Stats) GetThreePointFGM() int32 {
	if m != nil {
		return m.ThreePointFGM
	}
	return 0
}

func (m *Stats) GetFreeThrowsAttempted() int32 {
	if m != nil {
		return m.FreeThrowsAttempted
	}
	return 0
}

func (m *Stats) GetFreeThrowsMade() int32 {
	if m != nil {
		return m.FreeThrowsMade
	}
	return 0
}

func (m *Stats) GetOffensiveRebounds() int32 {
	if m != nil {
		return m.OffensiveRebounds
	}
	return 0
}

func (m *Stats) GetDefensiveRebounds() int32 {
	if m != nil {
		return m.DefensiveRebounds
	}
	return 0
}

func (m *Stats) GetAssists() int32 {
	if m != nil {
		return m.Assists
	}
	return 0
}

func (m *Stats) GetBlocks() int32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *Stats) GetSteals() int32 {
	if m != nil {
		return m.Steals
	}
	return 0
}

func (m *Stats) GetTurnovers() int32 {
	if m != nil {
		return m.Turnovers
	}
	return 0
}

func (m *Stats) GetRegularFoulsForced() int32 {
	if m != nil {
		return m.RegularFoulsForced
	}
	return 0
}

func (m *Stats) GetRegularFoulsCommitted() int32 {
	if m != nil {
		return m.RegularFoulsCommitted
	}
	return 0
}

func (m *Stats) GetTechnicalFoulsCommitted() int32 {
	if m != nil {
		return m.TechnicalFoulsCommitted
	}
	return 0
}

func (m *Stats) GetMinutesPlayed() int32 {
	if m != nil {
		return m.MinutesPlayed
	}
	return 0
}

type PlayerProfile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"`
	YearStarted          int32    `protobuf:"varint,2,opt,name=YearStarted,proto3" json:"YearStarted"`
	Position             string   `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerProfile) Reset()         { *m = PlayerProfile{} }
func (m *PlayerProfile) String() string { return proto.CompactTextString(m) }
func (*PlayerProfile) ProtoMessage()    {}
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{7}
}
func (m *PlayerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerProfile.Unmarshal(m, b)
}
func (m *PlayerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerProfile.Marshal(b, m, deterministic)
}
func (dst *PlayerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerProfile.Merge(dst, src)
}
func (m *PlayerProfile) XXX_Size() int {
	return xxx_messageInfo_PlayerProfile.Size(m)
}
func (m *PlayerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerProfile proto.InternalMessageInfo

func (m *PlayerProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerProfile) GetYearStarted() int32 {
	if m != nil {
		return m.YearStarted
	}
	return 0
}

func (m *PlayerProfile) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *PlayerProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PlayerGameStats struct {
	Player               *Player     `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player"`
	Team                 *PlayerTeam `protobuf:"bytes,2,opt,name=Team,proto3" json:"Team"`
	Stats                *Stats      `protobuf:"bytes,3,opt,name=Stats,proto3" json:"Stats"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerGameStats) Reset()         { *m = PlayerGameStats{} }
func (m *PlayerGameStats) String() string { return proto.CompactTextString(m) }
func (*PlayerGameStats) ProtoMessage()    {}
func (*PlayerGameStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{8}
}
func (m *PlayerGameStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerGameStats.Unmarshal(m, b)
}
func (m *PlayerGameStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerGameStats.Marshal(b, m, deterministic)
}
func (dst *PlayerGameStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerGameStats.Merge(dst, src)
}
func (m *PlayerGameStats) XXX_Size() int {
	return xxx_messageInfo_PlayerGameStats.Size(m)
}
func (m *PlayerGameStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerGameStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerGameStats proto.InternalMessageInfo

func (m *PlayerGameStats) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerGameStats) GetTeam() *PlayerTeam {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *PlayerGameStats) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type PlayerTeam struct {
	Team                 *Team    `protobuf:"bytes,1,opt,name=Team,proto3" json:"Team"`
	JerseyNumber         int32    `protobuf:"varint,2,opt,name=JerseyNumber,proto3" json:"JerseyNumber"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerTeam) Reset()         { *m = PlayerTeam{} }
func (m *PlayerTeam) String() string { return proto.CompactTextString(m) }
func (*PlayerTeam) ProtoMessage()    {}
func (*PlayerTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{9}
}
func (m *PlayerTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerTeam.Unmarshal(m, b)
}
func (m *PlayerTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerTeam.Marshal(b, m, deterministic)
}
func (dst *PlayerTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerTeam.Merge(dst, src)
}
func (m *PlayerTeam) XXX_Size() int {
	return xxx_messageInfo_PlayerTeam.Size(m)
}
func (m *PlayerTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerTeam.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerTeam proto.InternalMessageInfo

func (m *PlayerTeam) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *PlayerTeam) GetJerseyNumber() int32 {
	if m != nil {
		return m.JerseyNumber
	}
	return 0
}

type Game struct {
	GameId               int32        `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId"`
	HomeTeam             *Team        `protobuf:"bytes,2,opt,name=HomeTeam,proto3" json:"HomeTeam"`
	AwayTeam             *Team        `protobuf:"bytes,3,opt,name=AwayTeam,proto3" json:"AwayTeam"`
	Location             *Location    `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location"`
	Competition          *Competition `protobuf:"bytes,5,opt,name=Competition,proto3" json:"Competition"`
	Result               *GameResult  `protobuf:"bytes,6,opt,name=Result,proto3" json:"Result"`
	GameTime             string       `protobuf:"bytes,7,opt,name=GameTime,proto3" json:"GameTime"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{10}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (dst *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(dst, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *Game) GetHomeTeam() *Team {
	if m != nil {
		return m.HomeTeam
	}
	return nil
}

func (m *Game) GetAwayTeam() *Team {
	if m != nil {
		return m.AwayTeam
	}
	return nil
}

func (m *Game) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Game) GetCompetition() *Competition {
	if m != nil {
		return m.Competition
	}
	return nil
}

func (m *Game) GetResult() *GameResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Game) GetGameTime() string {
	if m != nil {
		return m.GameTime
	}
	return ""
}

type GameResult struct {
	HomeTeamId           int32    `protobuf:"varint,1,opt,name=HomeTeamId,proto3" json:"HomeTeamId"`
	HomeTeamPoints       int32    `protobuf:"varint,2,opt,name=HomeTeamPoints,proto3" json:"HomeTeamPoints"`
	AwayTeamId           int32    `protobuf:"varint,3,opt,name=AwayTeamId,proto3" json:"AwayTeamId"`
	AwayTeamPoints       int32    `protobuf:"varint,4,opt,name=AwayTeamPoints,proto3" json:"AwayTeamPoints"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResult) Reset()         { *m = GameResult{} }
func (m *GameResult) String() string { return proto.CompactTextString(m) }
func (*GameResult) ProtoMessage()    {}
func (*GameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{11}
}
func (m *GameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResult.Unmarshal(m, b)
}
func (m *GameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResult.Marshal(b, m, deterministic)
}
func (dst *GameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResult.Merge(dst, src)
}
func (m *GameResult) XXX_Size() int {
	return xxx_messageInfo_GameResult.Size(m)
}
func (m *GameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameResult proto.InternalMessageInfo

func (m *GameResult) GetHomeTeamId() int32 {
	if m != nil {
		return m.HomeTeamId
	}
	return 0
}

func (m *GameResult) GetHomeTeamPoints() int32 {
	if m != nil {
		return m.HomeTeamPoints
	}
	return 0
}

func (m *GameResult) GetAwayTeamId() int32 {
	if m != nil {
		return m.AwayTeamId
	}
	return 0
}

func (m *GameResult) GetAwayTeamPoints() int32 {
	if m != nil {
		return m.AwayTeamPoints
	}
	return 0
}

type PlayerInfo struct {
	PlayerId             int32          `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	Profile              *PlayerProfile `protobuf:"bytes,2,opt,name=Profile,proto3" json:"Profile"`
	Teams                []*PlayerTeam  `protobuf:"bytes,3,rep,name=Teams,proto3" json:"Teams"`
	StatTotals           *Stats         `protobuf:"bytes,4,opt,name=StatTotals,proto3" json:"StatTotals"`
	TotalGamesPlayed     int32          `protobuf:"varint,5,opt,name=TotalGamesPlayed,proto3" json:"TotalGamesPlayed"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{12}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerInfo) GetProfile() *PlayerProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *PlayerInfo) GetTeams() []*PlayerTeam {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *PlayerInfo) GetStatTotals() *Stats {
	if m != nil {
		return m.StatTotals
	}
	return nil
}

func (m *PlayerInfo) GetTotalGamesPlayed() int32 {
	if m != nil {
		return m.TotalGamesPlayed
	}
	return 0
}

type TeamInfo struct {
	Team                 *Team         `protobuf:"bytes,1,opt,name=Team,proto3" json:"Team"`
	Players              []*PlayerInfo `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TeamInfo) Reset()         { *m = TeamInfo{} }
func (m *TeamInfo) String() string { return proto.CompactTextString(m) }
func (*TeamInfo) ProtoMessage()    {}
func (*TeamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{13}
}
func (m *TeamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamInfo.Unmarshal(m, b)
}
func (m *TeamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamInfo.Marshal(b, m, deterministic)
}
func (dst *TeamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamInfo.Merge(dst, src)
}
func (m *TeamInfo) XXX_Size() int {
	return xxx_messageInfo_TeamInfo.Size(m)
}
func (m *TeamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeamInfo proto.InternalMessageInfo

func (m *TeamInfo) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *TeamInfo) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

type GameInfo struct {
	Game                 *Game              `protobuf:"bytes,1,opt,name=Game,proto3" json:"Game"`
	PlayerStats          []*PlayerGameStats `protobuf:"bytes,2,rep,name=PlayerStats,proto3" json:"PlayerStats"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GameInfo) Reset()         { *m = GameInfo{} }
func (m *GameInfo) String() string { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()    {}
func (*GameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{14}
}
func (m *GameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfo.Unmarshal(m, b)
}
func (m *GameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfo.Marshal(b, m, deterministic)
}
func (dst *GameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfo.Merge(dst, src)
}
func (m *GameInfo) XXX_Size() int {
	return xxx_messageInfo_GameInfo.Size(m)
}
func (m *GameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfo proto.InternalMessageInfo

func (m *GameInfo) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func (m *GameInfo) GetPlayerStats() []*PlayerGameStats {
	if m != nil {
		return m.PlayerStats
	}
	return nil
}

type CompetitionInfo struct {
	Competition          *Competition       `protobuf:"bytes,1,opt,name=Competition,proto3" json:"Competition"`
	RecentGames          []*Game            `protobuf:"bytes,2,rep,name=RecentGames,proto3" json:"RecentGames"`
	Locations            []*Location        `protobuf:"bytes,3,rep,name=Locations,proto3" json:"Locations"`
	Teams                []*Team            `protobuf:"bytes,4,rep,name=Teams,proto3" json:"Teams"`
	Standings            []*CompetitionTeam `protobuf:"bytes,5,rep,name=Standings,proto3" json:"Standings"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CompetitionInfo) Reset()         { *m = CompetitionInfo{} }
func (m *CompetitionInfo) String() string { return proto.CompactTextString(m) }
func (*CompetitionInfo) ProtoMessage()    {}
func (*CompetitionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{15}
}
func (m *CompetitionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompetitionInfo.Unmarshal(m, b)
}
func (m *CompetitionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompetitionInfo.Marshal(b, m, deterministic)
}
func (dst *CompetitionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompetitionInfo.Merge(dst, src)
}
func (m *CompetitionInfo) XXX_Size() int {
	return xxx_messageInfo_CompetitionInfo.Size(m)
}
func (m *CompetitionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CompetitionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CompetitionInfo proto.InternalMessageInfo

func (m *CompetitionInfo) GetCompetition() *Competition {
	if m != nil {
		return m.Competition
	}
	return nil
}

func (m *CompetitionInfo) GetRecentGames() []*Game {
	if m != nil {
		return m.RecentGames
	}
	return nil
}

func (m *CompetitionInfo) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *CompetitionInfo) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *CompetitionInfo) GetStandings() []*CompetitionTeam {
	if m != nil {
		return m.Standings
	}
	return nil
}

type GetPlayerInfoRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerInfoRequest) Reset()         { *m = GetPlayerInfoRequest{} }
func (m *GetPlayerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerInfoRequest) ProtoMessage()    {}
func (*GetPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{16}
}
func (m *GetPlayerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerInfoRequest.Unmarshal(m, b)
}
func (m *GetPlayerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetPlayerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerInfoRequest.Merge(dst, src)
}
func (m *GetPlayerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerInfoRequest.Size(m)
}
func (m *GetPlayerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerInfoRequest proto.InternalMessageInfo

func (m *GetPlayerInfoRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type GetGameInfoRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameInfoRequest) Reset()         { *m = GetGameInfoRequest{} }
func (m *GetGameInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetGameInfoRequest) ProtoMessage()    {}
func (*GetGameInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{17}
}
func (m *GetGameInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameInfoRequest.Unmarshal(m, b)
}
func (m *GetGameInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetGameInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameInfoRequest.Merge(dst, src)
}
func (m *GetGameInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetGameInfoRequest.Size(m)
}
func (m *GetGameInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameInfoRequest proto.InternalMessageInfo

func (m *GetGameInfoRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type GetTeamInfoRequest struct {
	TeamId               int32    `protobuf:"varint,1,opt,name=TeamId,proto3" json:"TeamId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeamInfoRequest) Reset()         { *m = GetTeamInfoRequest{} }
func (m *GetTeamInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTeamInfoRequest) ProtoMessage()    {}
func (*GetTeamInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{18}
}
func (m *GetTeamInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamInfoRequest.Unmarshal(m, b)
}
func (m *GetTeamInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetTeamInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamInfoRequest.Merge(dst, src)
}
func (m *GetTeamInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTeamInfoRequest.Size(m)
}
func (m *GetTeamInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamInfoRequest proto.InternalMessageInfo

func (m *GetTeamInfoRequest) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

type GetCompetitionInfoRequest struct {
	CompetitionId        int32    `protobuf:"varint,1,opt,name=CompetitionId,proto3" json:"CompetitionId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompetitionInfoRequest) Reset()         { *m = GetCompetitionInfoRequest{} }
func (m *GetCompetitionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompetitionInfoRequest) ProtoMessage()    {}
func (*GetCompetitionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heroball_47d898ed39240387, []int{19}
}
func (m *GetCompetitionInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompetitionInfoRequest.Unmarshal(m, b)
}
func (m *GetCompetitionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompetitionInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetCompetitionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompetitionInfoRequest.Merge(dst, src)
}
func (m *GetCompetitionInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompetitionInfoRequest.Size(m)
}
func (m *GetCompetitionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompetitionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompetitionInfoRequest proto.InternalMessageInfo

func (m *GetCompetitionInfoRequest) GetCompetitionId() int32 {
	if m != nil {
		return m.CompetitionId
	}
	return 0
}

func init() {
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*League)(nil), "pb.League")
	proto.RegisterType((*Competition)(nil), "pb.Competition")
	proto.RegisterType((*Team)(nil), "pb.Team")
	proto.RegisterType((*CompetitionTeam)(nil), "pb.CompetitionTeam")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Stats)(nil), "pb.Stats")
	proto.RegisterType((*PlayerProfile)(nil), "pb.PlayerProfile")
	proto.RegisterType((*PlayerGameStats)(nil), "pb.PlayerGameStats")
	proto.RegisterType((*PlayerTeam)(nil), "pb.PlayerTeam")
	proto.RegisterType((*Game)(nil), "pb.Game")
	proto.RegisterType((*GameResult)(nil), "pb.GameResult")
	proto.RegisterType((*PlayerInfo)(nil), "pb.PlayerInfo")
	proto.RegisterType((*TeamInfo)(nil), "pb.TeamInfo")
	proto.RegisterType((*GameInfo)(nil), "pb.GameInfo")
	proto.RegisterType((*CompetitionInfo)(nil), "pb.CompetitionInfo")
	proto.RegisterType((*GetPlayerInfoRequest)(nil), "pb.GetPlayerInfoRequest")
	proto.RegisterType((*GetGameInfoRequest)(nil), "pb.GetGameInfoRequest")
	proto.RegisterType((*GetTeamInfoRequest)(nil), "pb.GetTeamInfoRequest")
	proto.RegisterType((*GetCompetitionInfoRequest)(nil), "pb.GetCompetitionInfoRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HeroBallServiceClient is the client API for HeroBallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeroBallServiceClient interface {
	GetPlayerInfo(ctx context.Context, in *GetPlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfo, error)
	GetTeamInfo(ctx context.Context, in *GetTeamInfoRequest, opts ...grpc.CallOption) (*TeamInfo, error)
	GetGameInfo(ctx context.Context, in *GetGameInfoRequest, opts ...grpc.CallOption) (*GameInfo, error)
	GetCompetitionInfo(ctx context.Context, in *GetCompetitionInfoRequest, opts ...grpc.CallOption) (*CompetitionInfo, error)
}

type heroBallServiceClient struct {
	cc *grpc.ClientConn
}

func NewHeroBallServiceClient(cc *grpc.ClientConn) HeroBallServiceClient {
	return &heroBallServiceClient{cc}
}

func (c *heroBallServiceClient) GetPlayerInfo(ctx context.Context, in *GetPlayerInfoRequest, opts ...grpc.CallOption) (*PlayerInfo, error) {
	out := new(PlayerInfo)
	err := c.cc.Invoke(ctx, "/pb.HeroBallService/GetPlayerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heroBallServiceClient) GetTeamInfo(ctx context.Context, in *GetTeamInfoRequest, opts ...grpc.CallOption) (*TeamInfo, error) {
	out := new(TeamInfo)
	err := c.cc.Invoke(ctx, "/pb.HeroBallService/GetTeamInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heroBallServiceClient) GetGameInfo(ctx context.Context, in *GetGameInfoRequest, opts ...grpc.CallOption) (*GameInfo, error) {
	out := new(GameInfo)
	err := c.cc.Invoke(ctx, "/pb.HeroBallService/GetGameInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heroBallServiceClient) GetCompetitionInfo(ctx context.Context, in *GetCompetitionInfoRequest, opts ...grpc.CallOption) (*CompetitionInfo, error) {
	out := new(CompetitionInfo)
	err := c.cc.Invoke(ctx, "/pb.HeroBallService/GetCompetitionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeroBallServiceServer is the server API for HeroBallService service.
type HeroBallServiceServer interface {
	GetPlayerInfo(context.Context, *GetPlayerInfoRequest) (*PlayerInfo, error)
	GetTeamInfo(context.Context, *GetTeamInfoRequest) (*TeamInfo, error)
	GetGameInfo(context.Context, *GetGameInfoRequest) (*GameInfo, error)
	GetCompetitionInfo(context.Context, *GetCompetitionInfoRequest) (*CompetitionInfo, error)
}

func RegisterHeroBallServiceServer(s *grpc.Server, srv HeroBallServiceServer) {
	s.RegisterService(&_HeroBallService_serviceDesc, srv)
}

func _HeroBallService_GetPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeroBallServiceServer).GetPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HeroBallService/GetPlayerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeroBallServiceServer).GetPlayerInfo(ctx, req.(*GetPlayerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeroBallService_GetTeamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeroBallServiceServer).GetTeamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HeroBallService/GetTeamInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeroBallServiceServer).GetTeamInfo(ctx, req.(*GetTeamInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeroBallService_GetGameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeroBallServiceServer).GetGameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HeroBallService/GetGameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeroBallServiceServer).GetGameInfo(ctx, req.(*GetGameInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeroBallService_GetCompetitionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeroBallServiceServer).GetCompetitionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HeroBallService/GetCompetitionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeroBallServiceServer).GetCompetitionInfo(ctx, req.(*GetCompetitionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeroBallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HeroBallService",
	HandlerType: (*HeroBallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerInfo",
			Handler:    _HeroBallService_GetPlayerInfo_Handler,
		},
		{
			MethodName: "GetTeamInfo",
			Handler:    _HeroBallService_GetTeamInfo_Handler,
		},
		{
			MethodName: "GetGameInfo",
			Handler:    _HeroBallService_GetGameInfo_Handler,
		},
		{
			MethodName: "GetCompetitionInfo",
			Handler:    _HeroBallService_GetCompetitionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heroball.proto",
}

func init() { proto.RegisterFile("heroball.proto", fileDescriptor_heroball_47d898ed39240387) }

var fileDescriptor_heroball_47d898ed39240387 = []byte{
	// 1183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0x5f, 0x4f, 0x2b, 0x45,
	0x14, 0x4f, 0x69, 0x0b, 0xed, 0x59, 0xfe, 0x0e, 0x57, 0x5c, 0x09, 0x17, 0xc9, 0x48, 0x6e, 0x10,
	0x6f, 0xa8, 0x54, 0x4d, 0x8c, 0x0f, 0x26, 0xdc, 0x4b, 0xe8, 0xc5, 0x00, 0xe2, 0xd2, 0xc4, 0xdc,
	0x27, 0xb3, 0x6d, 0x0f, 0x65, 0xc3, 0xee, 0x4e, 0xdd, 0x99, 0x42, 0xf0, 0x4d, 0x7d, 0xf4, 0xd1,
	0xf8, 0xe6, 0xa7, 0xd2, 0xaf, 0xe0, 0xbb, 0x5f, 0xc1, 0xcc, 0xbf, 0xdd, 0xe9, 0xb6, 0xe0, 0x7d,
	0x62, 0xce, 0xef, 0x9c, 0xf9, 0x9d, 0x33, 0xe7, 0x5f, 0x17, 0x58, 0xbe, 0xc1, 0x8c, 0xf5, 0xc2,
	0x38, 0x3e, 0x18, 0x65, 0x4c, 0x30, 0x32, 0x37, 0xea, 0x6d, 0x6e, 0x0d, 0x19, 0x1b, 0xc6, 0xd8,
	0x0a, 0x47, 0x51, 0x2b, 0x4c, 0x53, 0x26, 0x42, 0x11, 0xb1, 0x94, 0x6b, 0x0b, 0xda, 0x85, 0xf9,
	0xcb, 0x38, 0x7c, 0xc0, 0x8c, 0x6c, 0x42, 0x43, 0x9f, 0x4e, 0x07, 0x7e, 0x65, 0xa7, 0xb2, 0x57,
	0x0f, 0x72, 0x99, 0x10, 0xa8, 0x5d, 0x84, 0x09, 0xfa, 0x73, 0x3b, 0x95, 0xbd, 0x66, 0xa0, 0xce,
	0xca, 0x9e, 0xf1, 0x48, 0x92, 0xf9, 0x55, 0x85, 0xe7, 0xb2, 0x64, 0x3d, 0xc3, 0x70, 0x38, 0x56,
	0x56, 0xfa, 0x54, 0xb0, 0x5a, 0xf9, 0x31, 0xd6, 0xe3, 0xe8, 0x2e, 0xe2, 0x0e, 0xab, 0x95, 0xe9,
	0x2d, 0x78, 0xaf, 0x59, 0x32, 0x42, 0xa1, 0x9c, 0x10, 0x6a, 0x9d, 0x28, 0x62, 0xaf, 0x0d, 0x07,
	0xa3, 0xde, 0x81, 0x46, 0x02, 0xeb, 0x7e, 0x17, 0x96, 0x9c, 0x2b, 0xa7, 0x03, 0xe5, 0xab, 0x1e,
	0x4c, 0x82, 0x79, 0x20, 0xd5, 0x22, 0x10, 0xda, 0x86, 0x5a, 0x17, 0xc3, 0x84, 0x6c, 0xc0, 0xbc,
	0xfc, 0x9b, 0x87, 0x6f, 0xa4, 0x59, 0xc1, 0xd3, 0x5b, 0x58, 0x71, 0x88, 0xd5, 0xf5, 0x2d, 0x4d,
	0x63, 0x42, 0x6c, 0xc8, 0x10, 0xa5, 0x1c, 0x68, 0xf2, 0x55, 0xa8, 0x7e, 0xcf, 0x52, 0x13, 0x94,
	0x3c, 0x92, 0x67, 0x50, 0x3f, 0xce, 0xc2, 0x7b, 0xfd, 0xf8, 0x7a, 0xa0, 0x05, 0xe9, 0xec, 0x8c,
	0x71, 0xe1, 0xd7, 0x14, 0xa8, 0xce, 0xf4, 0x6b, 0x68, 0x9c, 0xb1, 0xbe, 0x2a, 0x26, 0xd9, 0x06,
	0xb0, 0xe7, 0x3c, 0x50, 0x07, 0x99, 0x19, 0xec, 0x1f, 0x75, 0xa8, 0x5f, 0x89, 0x50, 0x70, 0xe2,
	0xc3, 0x82, 0x3a, 0xe4, 0x57, 0xad, 0x48, 0x76, 0xc0, 0xeb, 0xde, 0xb3, 0x4b, 0x16, 0xa5, 0xe2,
	0xa4, 0x73, 0x64, 0xe2, 0x74, 0xa1, 0x49, 0x8b, 0x73, 0x13, 0xb5, 0x0b, 0xc9, 0x12, 0x74, 0x6f,
	0x32, 0xc4, 0x9c, 0x45, 0x3f, 0x62, 0x12, 0x2c, 0x5b, 0x9d, 0xfb, 0xf5, 0x69, 0xab, 0x73, 0xf2,
	0x29, 0xac, 0x9f, 0x64, 0x88, 0xdd, 0x9b, 0x8c, 0xdd, 0xf3, 0x23, 0x21, 0x30, 0x19, 0x09, 0x1c,
	0xf8, 0xf3, 0xca, 0x76, 0x96, 0x8a, 0xbc, 0x80, 0xe5, 0x02, 0x3e, 0x0f, 0x07, 0xe8, 0x2f, 0x28,
	0xe3, 0x12, 0x4a, 0x5e, 0xc2, 0xda, 0xb7, 0xd7, 0xd7, 0x98, 0xf2, 0xe8, 0x0e, 0x03, 0xec, 0xb1,
	0x71, 0x3a, 0xe0, 0x7e, 0x43, 0x99, 0x4e, 0x2b, 0xa4, 0xf5, 0x31, 0x96, 0xad, 0x9b, 0xda, 0x7a,
	0x4a, 0x21, 0xf3, 0x7b, 0xc4, 0x79, 0xc4, 0x05, 0xf7, 0x41, 0xe7, 0xd7, 0x88, 0xb2, 0xb9, 0x5e,
	0xc5, 0xac, 0x7f, 0xcb, 0x7d, 0x4f, 0x37, 0x97, 0x96, 0x24, 0x7e, 0x25, 0x30, 0x8c, 0xb9, 0xbf,
	0xa8, 0x71, 0x2d, 0x91, 0x2d, 0x68, 0x76, 0xc7, 0x59, 0xca, 0xee, 0x30, 0xe3, 0xfe, 0x92, 0x52,
	0x15, 0x00, 0x39, 0x00, 0x12, 0xe0, 0x70, 0x1c, 0x87, 0xd9, 0x09, 0x1b, 0xc7, 0xfc, 0x84, 0x65,
	0x7d, 0x1c, 0xf8, 0xcb, 0xca, 0x6c, 0x86, 0x86, 0x7c, 0x0e, 0xef, 0xb9, 0xe8, 0x6b, 0x96, 0x24,
	0x91, 0x90, 0xf9, 0x5c, 0x51, 0x57, 0x66, 0x2b, 0xc9, 0x97, 0xf0, 0x7e, 0x17, 0xfb, 0x37, 0x69,
	0xd4, 0x0f, 0xe3, 0xd2, 0xbd, 0x55, 0x75, 0xef, 0x31, 0xb5, 0xac, 0xf1, 0x79, 0x94, 0x8e, 0x05,
	0x72, 0xb5, 0x58, 0x06, 0xfe, 0x9a, 0xae, 0xf1, 0x04, 0x48, 0x7f, 0xad, 0xc0, 0x92, 0x5e, 0x3c,
	0x97, 0x19, 0xbb, 0x8e, 0x62, 0xcc, 0xbb, 0xb7, 0xe2, 0xec, 0x89, 0x1d, 0xf0, 0xde, 0x62, 0x98,
	0x5d, 0x89, 0x30, 0x93, 0x9e, 0x4d, 0x67, 0x3a, 0xd0, 0x53, 0xfb, 0x49, 0xde, 0x3e, 0x46, 0xde,
	0xcf, 0xa2, 0x91, 0x52, 0xd7, 0x94, 0xda, 0x85, 0xe8, 0x4f, 0xb0, 0xa2, 0x83, 0xe8, 0x84, 0x09,
	0xea, 0x31, 0xa1, 0x76, 0x55, 0xba, 0xfb, 0x46, 0x23, 0x81, 0x5d, 0xa2, 0xd4, 0x8c, 0xfb, 0x9c,
	0xb2, 0x58, 0x2e, 0x2c, 0x9c, 0xa1, 0xff, 0xd0, 0xcc, 0x9d, 0x8a, 0xca, 0x6b, 0x37, 0xa5, 0x91,
	0x02, 0x02, 0x8d, 0xd3, 0x0b, 0x80, 0xe2, 0xd2, 0xff, 0x6c, 0x10, 0x0a, 0x8b, 0xdf, 0x60, 0xc6,
	0xf1, 0xe1, 0x62, 0x9c, 0xf4, 0x30, 0x33, 0x89, 0x98, 0xc0, 0xe8, 0x6f, 0x73, 0x50, 0x93, 0xcf,
	0x90, 0x6d, 0x25, 0xff, 0x16, 0xbb, 0x4c, 0x4b, 0x64, 0x17, 0x1a, 0x6f, 0x58, 0x82, 0x4e, 0xe4,
	0x85, 0x9b, 0x5c, 0x23, 0xad, 0x8e, 0xee, 0xc3, 0x07, 0x65, 0x55, 0x2d, 0x5b, 0x59, 0x0d, 0xd9,
	0x2b, 0xd6, 0x92, 0xca, 0xab, 0xd7, 0x5e, 0x54, 0x7b, 0xd9, 0x60, 0x41, 0xb1, 0xb4, 0x0e, 0x27,
	0xd6, 0xb9, 0x1a, 0x78, 0xaf, 0xbd, 0x22, 0x8d, 0x1d, 0x38, 0x98, 0x58, 0xf9, 0x2f, 0x60, 0x3e,
	0x40, 0x3e, 0x8e, 0x85, 0x1a, 0x79, 0x93, 0x60, 0xf9, 0x08, 0x8d, 0x06, 0x46, 0x2b, 0x6b, 0x2f,
	0xd1, 0x6e, 0x94, 0xe8, 0x79, 0x6f, 0x06, 0xb9, 0x4c, 0xff, 0xac, 0x00, 0x14, 0x57, 0xe4, 0xea,
	0xb4, 0x2f, 0x2c, 0x56, 0x67, 0x81, 0xc8, 0x05, 0x62, 0x25, 0xb5, 0x86, 0xb8, 0x49, 0x71, 0x09,
	0x95, 0x3c, 0x36, 0x07, 0xa7, 0x03, 0xb3, 0x07, 0x1d, 0x44, 0xf2, 0x58, 0xc9, 0xf0, 0xe8, 0x3d,
	0x58, 0x42, 0xe9, 0x5f, 0x15, 0x5b, 0xfd, 0xd3, 0xf4, 0x9a, 0x3d, 0xf9, 0xab, 0xfc, 0x09, 0x2c,
	0x98, 0x11, 0x31, 0x55, 0x5b, 0x2b, 0xfa, 0xcd, 0x28, 0x02, 0x6b, 0x41, 0x76, 0xa1, 0x2e, 0xbd,
	0xc8, 0xae, 0xab, 0xce, 0x68, 0x4d, 0xad, 0x24, 0x1f, 0x03, 0xc8, 0x1e, 0xec, 0x32, 0x21, 0x97,
	0x4f, 0xad, 0xdc, 0xa0, 0x8e, 0x92, 0xec, 0xc3, 0xaa, 0x3a, 0xc9, 0x5c, 0xda, 0x81, 0xd6, 0x4b,
	0x7b, 0x0a, 0xa7, 0x01, 0x34, 0x54, 0x1a, 0xe4, 0x8b, 0x9e, 0xee, 0xe7, 0x3d, 0x58, 0xd0, 0x51,
	0xc9, 0x3c, 0x97, 0x02, 0x95, 0xd7, 0x03, 0xab, 0xa6, 0x3f, 0xe8, 0x1a, 0x5b, 0xce, 0x8e, 0xdd,
	0x10, 0x86, 0x53, 0x95, 0x58, 0xb7, 0xfd, 0x17, 0xe0, 0xe9, 0x4b, 0x7a, 0xec, 0x34, 0xef, 0x7a,
	0xc1, 0x9b, 0x8f, 0x78, 0xe0, 0xda, 0xd1, 0x7f, 0x2b, 0x13, 0x3f, 0xe7, 0xca, 0x51, 0xa9, 0x67,
	0x2b, 0xef, 0xd0, 0xb3, 0xfb, 0xe0, 0x05, 0xd8, 0xc7, 0x54, 0xa8, 0x84, 0x18, 0xef, 0x45, 0x88,
	0xae, 0x92, 0xec, 0x43, 0xd3, 0x8e, 0x87, 0x2d, 0xd4, 0xe4, 0xf4, 0x14, 0x6a, 0xb2, 0x6d, 0x0b,
	0x5a, 0x2b, 0x18, 0xdd, 0x52, 0x1e, 0x42, 0xf3, 0x4a, 0x84, 0xe9, 0x20, 0x4a, 0x87, 0xdc, 0xaf,
	0x17, 0x6f, 0x2e, 0x7d, 0xa1, 0x04, 0x85, 0x15, 0x6d, 0xc3, 0xb3, 0x0e, 0x0a, 0x27, 0xd9, 0xf8,
	0xe3, 0x18, 0xb9, 0x78, 0xaa, 0x09, 0xe9, 0x4b, 0x20, 0x1d, 0x14, 0xb6, 0x12, 0xf6, 0xc6, 0x23,
	0x9b, 0xc6, 0x58, 0xdb, 0x5e, 0x70, 0xac, 0x67, 0x7d, 0x63, 0xd1, 0x23, 0xf8, 0xa0, 0x83, 0xa2,
	0x54, 0x03, 0x7b, 0x69, 0xea, 0xd3, 0xae, 0x32, 0xe3, 0xd3, 0xae, 0xfd, 0x73, 0x15, 0x56, 0xde,
	0x60, 0xc6, 0x5e, 0x85, 0x71, 0x7c, 0x85, 0xd9, 0x5d, 0xd4, 0x47, 0xf2, 0x16, 0x96, 0x26, 0x9e,
	0x49, 0x7c, 0x55, 0x8d, 0x19, 0x2f, 0xdf, 0x2c, 0x75, 0x1f, 0xdd, 0xfe, 0xe5, 0xef, 0x7f, 0x7e,
	0x9f, 0xf3, 0xe9, 0x7a, 0xeb, 0xee, 0xb0, 0x35, 0x44, 0xd1, 0x1a, 0x29, 0x5d, 0x2b, 0x4a, 0xaf,
	0xd9, 0x57, 0x95, 0x7d, 0xf2, 0x1d, 0x78, 0xce, 0xfb, 0xc8, 0x86, 0x21, 0x2e, 0x3d, 0x78, 0x73,
	0xd1, 0x16, 0x4b, 0x91, 0x6e, 0x29, 0xd2, 0x0d, 0xba, 0x66, 0x49, 0x05, 0x86, 0x49, 0x89, 0x32,
	0x6f, 0x75, 0x4b, 0x59, 0xca, 0xb8, 0xa6, 0xb4, 0xe0, 0x34, 0xe5, 0x30, 0x4c, 0x30, 0xa7, 0x4c,
	0x54, 0x15, 0xca, 0xbd, 0xfd, 0xdc, 0x30, 0xcf, 0xce, 0xf7, 0x66, 0xb9, 0x79, 0x94, 0x9f, 0x8f,
	0x94, 0x9f, 0xe7, 0xd4, 0xb7, 0x7e, 0xfa, 0x85, 0x81, 0x75, 0xd7, 0x9b, 0x57, 0xff, 0x6a, 0x7c,
	0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x70, 0x77, 0x0a, 0x9e, 0x0c, 0x00, 0x00,
}
